# from: https://github.com/vegasbrianc/prometheus/blob/master/alertmanager/config.yml
# https://prometheus.io/docs/alerting/latest/configuration/

global:
  # smtp_smarthost: "localhost:25"
  # smtp_from: "alertmanager@example.org"
  # slack_api_url: 'api.slack.com' # must be secret
  # telegram_api_url: "https://api.telegram.org"
  resolve_timeout: "5m"

# Files from which custom notification template definitions are read.
# The last component may use a wildcard matcher, e.g. 'templates/*.tmpl'.
templates:

# The root node of the routing tree.
route:
  receiver: "slack-notifications"
  group_by: [alertname, datacenter, app]
  
# A list of notification receivers.
receivers:
  - name: "slack-notifications"
    # slack_configs:
    #   - send_resolved: true
    #     username: "<username>"
    #     channel: "#alerts"
    #     api_url: "<incomming-webhook-url>"
    #     text: "Alert triggered for {{ .GroupLabels.app }}:\n{{ .GroupLabels.alertname }}."

# A list of inhibition rules.
inhibit_rules:

# A list of time intervals for muting/activating routes.
time_intervals:
