version: "3.9"

networks:
  monitoring-network: {}

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  api-server:
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    ports:
      - "8085:8085"
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring-network
    volumes:
      - ./Prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"