version: "3.9"

services:
  api-server:
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    ports:
      - "8085:8085"
    networks:
      - monitoring-network

networks:
  monitoring-network: {}