# https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml
# https://docs.docker.com/compose/production/
version: "3.9"

networks:
  monitoring-network: {}

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  # Our main application, the API built with F#.
  fsharp-api-server:
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    ports:
      - "8085:8085"
    networks:
      - monitoring-network
    restart: always

  # The main tool used to collect and store metrics data.
  # It uses the pull model.
  prometheus:
    image: prom/prometheus:v2.39.1
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.config.file=/etc/prometheus/web.yml"
    networks:
      - monitoring-network
    volumes:
      - ./Prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always

  # Grafana is the tool we use to create cool and instructive charts and graphs to
  # present the scraped data. It's critical to pick the right visualization category
  # in order to facilitate the process of identifying problems and their cause.
  grafana:
    image: grafana/grafana:8.5.22-ubuntu
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    user: "472"
    depends_on:
      - prometheus
    networks:
      - monitoring-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./Grafana/config.monitoring
    ports:
      - "3000:3000"
    restart: always

