# https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml
# https://docs.docker.com/compose/production/
services:
  fsharp-api-server:
    build: .
    container_name: fsharp-api
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    environment:
      - HOST=http://0.0.0.0
      - PORT=8085
      - MIN_LOG_LEVEL=INFO
    ports:
      - "8085:8085"
      - "9085:9085"
    networks:
      - monitoring-network
    restart: always

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.config.file=/etc/prometheus/web.yml"
    networks:
      - monitoring-network
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:8.5.22-ubuntu
    container_name: grafana
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    user: "472"
    depends_on:
      - prometheus
    networks:
      - monitoring-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - "3000:3000"
    restart: always

networks:
  monitoring-network: {}

volumes:
  prometheus_data: {}
  grafana_data: {}
