global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fsharp-api"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["api-server:8085"]
        labels:
          group: "production"