{
 "title": "Four golden signals",
 "description": "Custom dashboard for displaying the four golden signals for a .NET application",
 "tags": [
  "prometheus",
  "dotnet",
  "fsharp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average HTTP request duration (Latency)",
   "type": "timeseries",
   "description": "Latency signal",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_request_duration_seconds_sum[1m])) / sum(increase(api_request_duration_seconds_count[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "# Requests per time (Traffic)",
   "type": "timeseries",
   "description": "Traffic signal",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(api_request_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Errors by time (Errors)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "increase(api_request_count_total{status_code=~\"4..|5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "description": "Quantity of requests",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(api_request_count_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "description": "Quantity of error requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_request_count_total{status_code=~\"4..|5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory in MegaBytes",
   "type": "timeseries",
   "description": "Saturation signal",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "# Response codes by time (Traffic)",
   "type": "timeseries",
   "description": "This graph presents the quantity of requests that resulted in a specific response code (like 200, 201, 500, ...) during a time window ",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  increase(api_request_count_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(%) CPU Usage",
   "type": "timeseries",
   "description": "Saturation signal",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  system_runtime_cpu_usage\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "description": "Saturation signal",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  process_num_threads\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}