name: Build and Push Container

on:
  workflow_dispatch:

permissions:
  packages: write
    
jobs:
  build-and-push-container:
    name: Build and publish container
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker setup
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Create the tag
        run: |
          LAST_COMMIT_DT=$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y.%m.%d-%H.%M.%S)

          IMAGE="ghcr.io/64j0/fsharp-monitoring--api:${LAST_COMMIT_DT}"
          echo "FINAL_IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Build the container
        run: docker build . --target runtime --tag "${FINAL_IMAGE}"
      - name: Push the container
        run: docker push "${FINAL_IMAGE}"